#!/bin/bash

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew update

brew install bash-git-prompt
brew install ruby
brew install python
brew install imagemagick
brew install ansible
brew cask install sublime-text
brew cask install appcode
brew cask install google-chrome
brew cask install sourcetree
brew cask install slack
brew cask install virtualbox
brew cask install vagrant
brew cask install torbrowser
brew cask install backblaze

